import type { Application, StatusConfig, AccentPalette } from './types';

export const SEED_APPLICATIONS: Application[] = [
  {
    id: 'app-01',
    company: 'Datadog',
    logo: 'DD',
    logoColor: '#632CA6',
    role: 'Alternant Software Engineer',
    location: 'Paris 9e',
    remote: 'Hybride 2j',
    salary: '1 650 €',
    rhythm: '3 sem. entreprise / 1 sem. école',
    source: 'LinkedIn',
    sourceUrl: 'https://linkedin.com/jobs/...',
    contact: { name: 'Claire Moreau', role: 'Talent Acquisition', email: 'claire.m@datadog.com', phone: '' },
    status: 'interview',
    stepIndex: 3,
    interest: 5,
    favorite: true,
    urgent: true,
    sentAt: '2026-03-28',
    lastActionAt: '2026-04-18',
    interviewAt: '2026-04-27',
    nextAction: 'Préparer cas technique SRE',
    nextActionDue: '2026-04-26',
    notes: 'Très bon feeling avec Claire. Équipe observability, stack Go + Python. Ils attendent un cas technique pour le 27.',
    cv: 'CV_Leo_2026_v3.pdf',
    letter: 'LM_Datadog.pdf',
    tags: ['dev', 'saas', 'pref'],
  },
  {
    id: 'app-02',
    company: 'Doctolib',
    logo: 'Dt',
    logoColor: '#0BAE71',
    role: 'Product Designer Apprentice',
    location: 'Levallois',
    remote: 'Hybride 3j',
    salary: '1 500 €',
    rhythm: '1 sem / 1 sem',
    source: 'Welcome to the Jungle',
    sourceUrl: 'https://welcometothejungle.com/...',
    contact: { name: 'Idris Benali', role: 'Design Lead', email: 'idris@doctolib.com', phone: '' },
    status: 'offer',
    stepIndex: 4,
    interest: 4,
    favorite: true,
    urgent: true,
    sentAt: '2026-02-14',
    lastActionAt: '2026-04-22',
    interviewAt: '2026-04-10',
    nextAction: 'Répondre avant vendredi',
    nextActionDue: '2026-04-26',
    notes: 'Offre reçue. 1500€ + tickets resto. À comparer avec Datadog.',
    cv: 'CV_Leo_2026_v2.pdf',
    letter: 'LM_Doctolib.pdf',
    tags: ['design', 'health'],
  },
  {
    id: 'app-03',
    company: 'Alan',
    logo: 'Al',
    logoColor: '#FF4338',
    role: 'Data Analyst en alternance',
    location: 'Paris 2e',
    remote: 'Full remote possible',
    salary: '1 400 €',
    rhythm: '3j / 2j',
    source: 'Site carrière',
    sourceUrl: '',
    contact: { name: 'Noémie Schmidt', role: 'People', email: 'noemie@alan.com', phone: '' },
    status: 'relance',
    stepIndex: 1,
    interest: 3,
    favorite: false,
    urgent: false,
    sentAt: '2026-03-10',
    lastActionAt: '2026-04-02',
    interviewAt: null,
    nextAction: 'Relancer Noémie',
    nextActionDue: '2026-04-25',
    notes: 'Candidature envoyée il y a 5 semaines, pas de retour. Relance prévue.',
    cv: 'CV_Leo_2026_v2.pdf',
    letter: 'LM_Alan.pdf',
    tags: ['data', 'health'],
  },
  {
    id: 'app-04',
    company: 'Qonto',
    logo: 'Qo',
    logoColor: '#1D1D1B',
    role: 'Alternant Frontend Engineer',
    location: 'Paris 9e',
    remote: 'Hybride 2j',
    salary: '1 600 €',
    rhythm: '3 sem / 1 sem',
    source: 'Cooptation',
    sourceUrl: '',
    contact: { name: 'Théo Laurent', role: 'Ami / dev chez Qonto', email: 'theo.l@qonto.com', phone: '+33 6 12 34 56 78' },
    status: 'interview',
    stepIndex: 2,
    interest: 5,
    favorite: true,
    urgent: false,
    sentAt: '2026-04-02',
    lastActionAt: '2026-04-20',
    interviewAt: '2026-05-03',
    nextAction: 'Entretien RH lundi',
    nextActionDue: '2026-05-03',
    notes: 'Passé par Théo, entretien RH calé. Stack Ember → migration React en cours.',
    cv: 'CV_Leo_2026_v3.pdf',
    letter: 'LM_Qonto.pdf',
    tags: ['dev', 'fintech', 'pref'],
  },
  {
    id: 'app-05',
    company: 'Blablacar',
    logo: 'Bl',
    logoColor: '#00AFF5',
    role: 'Growth Marketing Apprentice',
    location: 'Paris 8e',
    remote: 'Hybride 2j',
    salary: '1 350 €',
    rhythm: '1 sem / 1 sem',
    source: 'LinkedIn',
    sourceUrl: '',
    contact: { name: 'Marion Fauré', role: 'Growth Lead', email: 'marion@blablacar.com', phone: '' },
    status: 'sent',
    stepIndex: 1,
    interest: 3,
    favorite: false,
    urgent: false,
    sentAt: '2026-04-15',
    lastActionAt: '2026-04-15',
    interviewAt: null,
    nextAction: 'Attendre retour',
    nextActionDue: null,
    notes: 'Candidature fraîche, offre correspond bien.',
    cv: 'CV_Leo_2026_v3.pdf',
    letter: 'LM_Blablacar.pdf',
    tags: ['marketing'],
  },
  {
    id: 'app-06',
    company: 'Swile',
    logo: 'Sw',
    logoColor: '#FF5C39',
    role: 'UX Designer en alternance',
    location: 'Montpellier / Paris',
    remote: 'Hybride flexible',
    salary: '1 450 €',
    rhythm: '3j / 2j',
    source: 'Salon Student',
    sourceUrl: '',
    contact: { name: 'Hugo Petit', role: 'Head of Design', email: 'hugo@swile.co', phone: '' },
    status: 'rejected',
    stepIndex: 4,
    interest: 4,
    favorite: false,
    urgent: false,
    sentAt: '2026-02-20',
    lastActionAt: '2026-03-30',
    interviewAt: '2026-03-25',
    nextAction: '',
    nextActionDue: null,
    notes: 'Refus après 2 entretiens. Feedback : manque d\'exp. recherche utilisateur. À retravailler.',
    cv: 'CV_Leo_2026_v1.pdf',
    letter: 'LM_Swile.pdf',
    tags: ['design'],
  },
  {
    id: 'app-07',
    company: 'Payfit',
    logo: 'Pf',
    logoColor: '#0F62FE',
    role: 'Alternant Product Manager',
    location: 'Paris 9e',
    remote: 'Hybride 2j',
    salary: '1 550 €',
    rhythm: '3 sem / 1 sem',
    source: 'LinkedIn',
    sourceUrl: '',
    contact: { name: 'Sarah Nguyen', role: 'Senior PM', email: 'sarah.n@payfit.com', phone: '' },
    status: 'sent',
    stepIndex: 1,
    interest: 4,
    favorite: true,
    urgent: false,
    sentAt: '2026-04-19',
    lastActionAt: '2026-04-19',
    interviewAt: null,
    nextAction: 'Relance dans 10j si silence',
    nextActionDue: '2026-04-29',
    notes: 'Le poste correspond à 100%, équipe Onboarding.',
    cv: 'CV_Leo_2026_v3.pdf',
    letter: 'LM_Payfit.pdf',
    tags: ['product', 'hr-tech'],
  },
  {
    id: 'app-08',
    company: 'Back Market',
    logo: 'Bm',
    logoColor: '#6FE599',
    role: 'Data Engineer Apprentice',
    location: 'Paris 2e',
    remote: 'Hybride 2j',
    salary: '1 500 €',
    rhythm: '3 sem / 1 sem',
    source: 'Indeed',
    sourceUrl: '',
    contact: { name: '', role: '', email: '', phone: '' },
    status: 'todo',
    stepIndex: 0,
    interest: 4,
    favorite: false,
    urgent: false,
    sentAt: null,
    lastActionAt: null,
    interviewAt: null,
    nextAction: 'Envoyer avant vendredi',
    nextActionDue: '2026-04-26',
    notes: 'À envoyer — CV à adapter.',
    cv: '',
    letter: '',
    tags: ['data', 'impact'],
  },
  {
    id: 'app-09',
    company: 'Lydia',
    logo: 'Ly',
    logoColor: '#0070F3',
    role: 'Mobile Engineer Apprentice',
    location: 'Paris 17e',
    remote: 'Hybride 2j',
    salary: '1 550 €',
    rhythm: '3 sem / 1 sem',
    source: 'Site carrière',
    sourceUrl: '',
    contact: { name: '', role: '', email: '', phone: '' },
    status: 'todo',
    stepIndex: 0,
    interest: 3,
    favorite: false,
    urgent: false,
    sentAt: null,
    lastActionAt: null,
    interviewAt: null,
    nextAction: 'Adapter CV mobile',
    nextActionDue: null,
    notes: '',
    cv: '',
    letter: '',
    tags: ['dev', 'fintech'],
  },
  {
    id: 'app-10',
    company: 'Contentsquare',
    logo: 'Cs',
    logoColor: '#3A12B2',
    role: 'Product Designer Apprentice',
    location: 'Paris 9e',
    remote: 'Hybride 3j',
    salary: '1 500 €',
    rhythm: '1 sem / 1 sem',
    source: 'LinkedIn',
    sourceUrl: '',
    contact: { name: 'Léa Dubois', role: 'Design Manager', email: 'lea.d@contentsquare.com', phone: '' },
    status: 'relance',
    stepIndex: 1,
    interest: 4,
    favorite: false,
    urgent: true,
    sentAt: '2026-03-20',
    lastActionAt: '2026-04-05',
    interviewAt: null,
    nextAction: 'Relancer aujourd\'hui',
    nextActionDue: '2026-04-24',
    notes: 'Relance due depuis 2 jours.',
    cv: 'CV_Leo_2026_v2.pdf',
    letter: 'LM_Contentsquare.pdf',
    tags: ['design'],
  },
  {
    id: 'app-11',
    company: 'Ledger',
    logo: 'Ld',
    logoColor: '#000000',
    role: 'Alternant Security Engineer',
    location: 'Paris 2e',
    remote: 'Hybride 2j',
    salary: '1 700 €',
    rhythm: '3 sem / 1 sem',
    source: 'Cooptation',
    sourceUrl: '',
    contact: { name: 'Antoine Roux', role: 'Security Lead', email: 'antoine@ledger.com', phone: '' },
    status: 'interview',
    stepIndex: 2,
    interest: 5,
    favorite: true,
    urgent: false,
    sentAt: '2026-03-18',
    lastActionAt: '2026-04-15',
    interviewAt: '2026-04-30',
    nextAction: 'Entretien technique',
    nextActionDue: '2026-04-30',
    notes: 'Gros challenge technique. Réviser crypto asymétrique, hardware wallets.',
    cv: 'CV_Leo_2026_v3.pdf',
    letter: 'LM_Ledger.pdf',
    tags: ['security', 'crypto'],
  },
  {
    id: 'app-12',
    company: 'Veepee',
    logo: 'Vp',
    logoColor: '#EC008C',
    role: 'Frontend Apprentice',
    location: 'La Plaine Saint-Denis',
    remote: 'Hybride 2j',
    salary: '1 400 €',
    rhythm: '3 sem / 1 sem',
    source: 'LinkedIn',
    sourceUrl: '',
    contact: { name: '', role: '', email: '', phone: '' },
    status: 'rejected',
    stepIndex: 1,
    interest: 2,
    favorite: false,
    urgent: false,
    sentAt: '2026-03-01',
    lastActionAt: '2026-03-15',
    interviewAt: null,
    nextAction: '',
    nextActionDue: null,
    notes: 'Refus auto après 2 semaines.',
    cv: 'CV_Leo_2026_v2.pdf',
    letter: 'LM_Veepee.pdf',
    tags: ['dev', 'ecom'],
  },
];

export const STATUSES: StatusConfig[] = [
  { id: 'todo',      label: 'À envoyer',  short: 'À envoyer', icon: 'edit',   gradient: 'linear-gradient(135deg, #E8ECF4 0%, #C9D2E3 100%)', solid: '#8892B0', text: '#1E2A44' },
  { id: 'sent',      label: 'Envoyée',    short: 'Envoyée',   icon: 'send',   gradient: 'linear-gradient(135deg, #B8E1FF 0%, #6BA3E8 100%)', solid: '#4A8FD9', text: '#0E2E52' },
  { id: 'relance',   label: 'À relancer', short: 'Relance',   icon: 'clock',  gradient: 'linear-gradient(135deg, #FFD6A5 0%, #FF9671 100%)', solid: '#FF7A45', text: '#5B2604' },
  { id: 'interview', label: 'Entretien',  short: 'Entretien', icon: 'star',   gradient: 'linear-gradient(135deg, #C2B6FF 0%, #7B61FF 100%)', solid: '#7B61FF', text: '#28166B' },
  { id: 'offer',     label: 'Offre !',    short: 'Offre',     icon: 'trophy', gradient: 'linear-gradient(135deg, #A6F4C5 0%, #12B981 100%)', solid: '#12B981', text: '#0B3A25' },
  { id: 'rejected',  label: 'Refusée',    short: 'Refusée',   icon: 'close',  gradient: 'linear-gradient(135deg, #FFCDD4 0%, #F27A8E 100%)', solid: '#E84A63', text: '#5B0F1F' },
];

export const STEP_LABELS = ['Brouillon', 'Envoi', '1er contact', 'Entretien', 'Décision'];

export const ACCENT_PALETTES: Record<string, AccentPalette> = {
  sunset: { a: '#FF5B8E', b: '#FFB547', c: '#7B61FF', name: 'Sunset' },
  forest: { a: '#12B981', b: '#4A8FD9', c: '#7B61FF', name: 'Forest' },
  berry:  { a: '#E84A63', b: '#7B61FF', c: '#0F62FE', name: 'Berry' },
  mono:   { a: '#1A1625', b: '#4A4358', c: '#8A8398', name: 'Mono' },
};
